org: mylocalhome
app: meet-agent-ai-node-back
service: meet-agent-ia-node-back
frameworkVersion: '4'

provider:
 name: aws
 runtime: nodejs20.x
 region: us-east-1
 deploymentBucket:
  name: meetai-deployment-${opt:stage, 'dev'}
 stage: ${opt:stage, 'dev'}
 http:
  cors:
   allowedOrigins:
    - https://master.647838cc.amplifyapp.com
    - http://localhost:3000
   allowedHeaders:
    - Content-Type
    - Authorization
    - Access-Control-Allow-Origin
   allowedMethods:
    - GET
    - POST
    - OPTIONS
   allowCredentials: true
  maxAge: 6000

 environment:
  USERS_TABLE: ${self:service}-${sls:stage}-user
  MEETS_TABLE: ${self:service}-${sls:stage}-meet
  JWT_SECRET: ${env:JWT_SECRET}

 iam:
  role:
   statements:
    - Effect: Allow
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
       - dynamodb:BatchWriteItem
       - s3:*
       - ssm:PutParameter
       - ssm:GetParameter
       - ssm:DeleteParameter
      Resource:
        - Fn::GetAtt: [UsersTable, Arn]
        - Fn::GetAtt: [MeetsTable, Arn]
        - '*'

functions:
  verifyToken: 
    handler: src/users/verifyToken.handler

  getUsers:
    handler: src/users/getUsers.handler
    events:
      - http:
          path: /users
          method: get
          authorizer:
            name: verifyToken
            type: TOKEN

  getUserId:
    handler: src/users/getUser.handler
    events:
      - http:
          path: /users/{id}
          method: get
          #authorizer:
            #name: verifyToken
            #type: TOKEN

  createUser:
    handler: src/users/createUser.handler
    events:
      - http:
          path: /users
          method: post
          authorizer:
            name: verifyToken
            type: TOKEN

  UpdateUser:
    handler: src/users/updateUser.handler
    events:
      - http:
          path: /users/{id}
          method: put
          authorizer:
            name: verifyToken
            type: TOKEN

  DeleteUser:
    handler: src/users/deleteUser.handler
    events:
      - http:
          path: /users/{id}
          method: delete
          authorizer:
            name: verifyToken
            type: TOKEN

  Login:
    handler: src/users/login.handler
    events:
      - http:
          path: /users/login
          method: post

  getMeets:
    handler: src/meets/getMeets.handler
    events:
      - http:
          path: /meets
          method: get
          authorizer:
            name: verifyToken
            type: TOKEN
  getMeet:
    handler: src/meets/getMeet.handler
    events:
      - http:
          path: /meets/{id}
          method: get
          authorizer:
            name: verifyToken
            type: TOKEN

  CreateMeet:
    handler: src/meets/createMeet.handler
    events:
      - http:
          path: /meet
          method: post
          authorizer:
            name: verifyToken
            type: TOKEN

  UpdateMeet:
    handler: src/meets/updateMeet.handler
    events:
      - http:
          path: /meets/{id}
          method: put
          authorizer:
            name: verifyToken
            type: TOKEN

  DeleteMeet:
    handler: src/meets/deleteMeet.handler
    events:
      - http:
          path: /meets/{id}
          method: delete
          authorizer:
            name: verifyToken
            type: TOKEN

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: '${self:provider.environment.USERS_TABLE}'
    MeetsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: '${self:provider.environment.MEETS_TABLE}'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
       


  

useDotenv: true
plugins:
 - serverless-offline

build:
 esbuild:
  bundle: true
  sourcemap: true
  target: node18
  platform: node
