org: mylocalhome
app: meet-agent-ai-node-back
service: meet-agent-ia-node-back
frameworkVersion: '4'

provider:
 name: aws
 runtime: nodejs20.x
 region: us-east-1
 deploymentBucket:
  name: meetai-deployment-${opt:stage, 'dev'}
 stage: ${opt:stage, 'dev'}
 httpApi:
  cors:
   allowedOrigins:
    - https://master.647838cc.amplifyapp.com
    - http://localhost:3000
   allowedHeaders:
    - Content-Type
    - Authorization
    - Access-Control-Allow-Origin
   allowedMethods:
    - GET
    - POST
    - OPTIONS
   allowCredentials: true
  maxAge: 6000

 environment:
  USERS_TABLE: ${self:service}-${sls:stage}-user

 iam:
  role:
   statements:
    - Effect: Allow
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
       - dynamodb:BatchWriteItem
       - s3:*
       - ssm:PutParameter
       - ssm:GetParameter
       - ssm:DeleteParameter
      Resource:
       - Fn::GetAtt: [UsersTable, Arn]
       - '*'

functions:
  getUsers:
    handler: src/users/getUsers.handler
    events:
      - httpApi:
          path: /users
          method: get

  getUserId:
    handler: src/users/getUser.handler
    events:
      - httpApi:
          path: /users/{id}
          method: get

  createUser:
    handler: src/users/createUser.handler
    events:
      - httpApi:
          path: /users
          method: post
  UpdateUser:
    handler: src/users/updateUser.handler
    events:
      - httpApi:
          path: /users/{id}
          method: put

  DeleteUser:
    handler: src/users/deleteUser.handler
    events:
      - httpApi:
          path: /users/{id}
          method: delete

resources:
 Resources:
  UsersTable:
   Type: AWS::DynamoDB::Table
   Properties:
    AttributeDefinitions:
     - AttributeName: id
       AttributeType: S
    KeySchema:
     - AttributeName: id
       KeyType: HASH
    ProvisionedThroughput:
     ReadCapacityUnits: 1
     WriteCapacityUnits: 1

    TableName: ${self:provider.environment.USERS_TABLE}
plugins:
 - serverless-offline

build:
 esbuild:
  bundle: true
  sourcemap: true
  target: node18
  platform: node
